/** The single schema declaration shared by every Memory repository session. */
export const MEMORY_WORKSPACE_COLLECTIONS = Object.freeze({
  actors: ['workspaceId', 'kind', 'canonicalName', 'status', 'updatedAt'],
  'actor-aliases': ['workspaceId', 'ownerId', 'normalizedValue', 'status', 'updatedAt'],
  'actor-candidates': ['workspaceId', 'chatKey', 'status', 'confidence', 'updatedAt'],
  locations: ['workspaceId', 'canonicalName', 'status', 'updatedAt'],
  'location-aliases': ['workspaceId', 'locationId', 'normalizedValue', 'status', 'updatedAt'],
  'location-candidates': ['workspaceId', 'chatKey', 'status', 'confidence', 'updatedAt'],
  'inventory-items': ['workspaceId', 'canonicalName', 'category', 'status', 'updatedAt'],
  'inventory-states': ['workspaceId', 'chatKey', 'itemId', 'measureKind', 'unitKey', 'availability', 'updatedAtFloor', 'updatedAt'],
  'inventory-events': ['workspaceId', 'chatKey', 'itemId', 'operation', 'measureKind', 'floor', 'occurredAt', 'recordedAt'],
  episodes: ['workspaceId', 'chatKey', 'floorStart', 'occurredAt', 'createdAt'],
  observations: ['workspaceId', 'chatKey', 'episodeId', 'sourceRef', 'speakerOwnerId', 'occurredAt'],
  facts: ['workspaceId', 'chatKey', 'status', 'kind', 'confidence', 'freshestEvidenceAt', 'updatedAt'],
  evidence: ['workspaceId', 'chatKey', 'factId', 'occurredAt'],
  'fact-heads': ['workspaceId', 'chatKey', 'slotKey', 'factId'],
  'memory-traces': ['workspaceId', 'chatKey', 'ownerId', 'factId', 'knowledgeMode', 'privacy', 'clarity', 'beliefConfidence', 'emotionalSalience', 'rehearsalCount', 'updatedAt'],
  'scene-casts': ['workspaceId', 'chatKey', 'floor', 'createdAt'],
  'capture-jobs': ['workspaceId', 'chatKey', 'status', 'updatedAt'],
  'capture-repair-queue': ['workspaceId', 'chatKey', 'jobId', 'status', 'batchIndex', 'updatedAt'],
  'memory-review-items': ['workspaceId', 'chatKey', 'pipelineRunId', 'stage', 'status', 'createdAt'],
  'change-audits': ['workspaceId', 'chatKey', 'createdAt'],
  'memory-details': ['workspaceId', 'chatKey', 'ownerId', 'traceId'],
  'memory-links': ['workspaceId', 'chatKey', 'ownerId', 'updatedAt'],
  'vector-index': ['workspaceId', 'chatKey', 'recordId', 'updatedAt'],
  profiles: ['workspaceId', 'ownerId', 'updatedAt'],
  'profile-claims': ['workspaceId', 'ownerId', 'level', 'updatedAt'],
  'relationship-claims': ['workspaceId', 'fromOwnerId', 'toOwnerId', 'updatedAt'],
  'recall-exposures': ['workspaceId', 'chatKey', 'ownerId', 'createdAt'],
  'dream-jobs': ['workspaceId', 'chatKey', 'ownerId', 'status', 'updatedAt'],
  'dream-audits': ['workspaceId', 'chatKey', 'ownerId', 'createdAt'],
  'dream-narratives': ['workspaceId', 'chatKey', 'ownerId', 'createdAt'],
  usage: ['chatKey', 'capturedAt'],
  'recall-logs': ['chatKey', 'createdAt'],
  'generation-recall-details': ['workspaceId', 'chatKey', 'messageId', 'messageIndex', 'variantId', 'createdAt'],
  'generation-prompt-snapshots': ['workspaceId', 'chatKey', 'detailId', 'createdAt'],
  'generation-prompt-snapshot-chunks': ['workspaceId', 'chatKey', 'snapshotId', 'index'],
  'graph-nodes': ['workspaceId', 'chatKey', 'entityKey', 'updatedAt'],
  'graph-edges': ['workspaceId', 'chatKey', 'fromNodeId', 'toNodeId', 'backingFactId', 'updatedAt'],
  'scene-states': ['workspaceId', 'chatKey', 'sceneId', 'updatedAtFloor', 'revision'],
  'scene-transitions': ['workspaceId', 'chatKey', 'sceneId', 'floor', 'reason'],
  'generation-cast-plans': ['workspaceId', 'chatKey', 'sceneId', 'basedOnFloor', 'createdAt', 'plannerMode', 'confidence'],
  'cast-plan-audits': ['workspaceId', 'chatKey', 'planId', 'result', 'createdAt'],
  'recall-coverage-logs': ['workspaceId', 'chatKey', 'planId', 'covered', 'createdAt'],
  'memory-usage-logs': ['workspaceId', 'chatKey', 'ownerId', 'traceId', 'usage', 'createdAt'],
} as const);
