import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

describe('Memory 工作台公共 UI 契约门禁', () => {
  it('只消费 SDK 公共标记和主题变量，不恢复内部类或基础控件副本', async () => {
    const [memoryUiSource, librarySource, inventoryThreeSource, inventoryModelSource, styles] = await Promise.all([
      readFile(new URL('../src/ui/memory-ui.ts', import.meta.url), 'utf8'),
      readFile(new URL('../src/ui/memory-library-view.ts', import.meta.url), 'utf8'),
      readFile(new URL('../src/ui/inventory-card-three.ts', import.meta.url), 'utf8'),
      readFile(new URL('../src/ui/inventory-workbench-model.ts', import.meta.url), 'utf8'),
      readFile(new URL('../src/ui/memory.css', import.meta.url), 'utf8'),
    ]);
    const source = `${memoryUiSource}\n${librarySource}`;

    expect(source).toContain('UI_CONTROL_ATTRIBUTE');
    expect(source).toContain('UI_CONTROL_SIZE_ATTRIBUTE');
    expect(source).toContain('UI_CONTROL_ICON_ONLY_ATTRIBUTE');
    expect(source).toContain('UI_CONTROL_TONE_ATTRIBUTE');
    expect(source).toContain("uiButton('neutral', 'xs', true)");
    expect(source).toContain("uiButton('neutral', 'sm', true)");
    expect(source).toContain("uiButton('primary', 'md')");
    expect(source).toContain('popupUi?.refreshControls(root)');
    expect(styles).toContain('--ss-control-input-padding-inline-start: 34px');
    expect(styles).toMatch(/\.stx-memory-workbench\s*\{[^}]*--ss-theme-surface:\s*#17191c[^}]*--ss-theme-surface-2:\s*#1d2024[^}]*--ss-theme-surface-3:\s*#23272c/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s*\{[^}]*--ss-theme-border:\s*#34383f[^}]*--ss-theme-accent:\s*#c5a059/u);
    expect(styles).toMatch(/\.stx-memory-page-content\s*\{[^}]*background:\s*var\(--stx-memory-content-surface\)/u);
    expect(styles).toMatch(/\.stx-memory-statusbar\s+\[data-ss-helper-control="status"\][^}]*justify-self:\s*start/u);
    expect(styles).toMatch(/\.stx-memory-statusbar\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1\.35fr\)\s+repeat\(6,/u);
    expect(styles).toMatch(/\.stx-memory-panel\s*>\s*p\.stx-memory-estimate-note\s*\{[^}]*margin:\s*14px\s+0\s+0/u);
    expect(styles).toContain('.stx-memory-workbench .stx-memory-panel > p.stx-memory-estimate-note { margin: 14px 0 0; }');
    expect(styles).toMatch(/\.stx-memory-chat-storage\s*\{[^}]*border-radius:\s*7px/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-maintenance-action\[data-ss-helper-control="button"\][^}]*display:\s*grid[^}]*grid-template-columns:\s*34px\s+minmax\(0,\s*1fr\)\s+20px/u);
    expect(styles).toMatch(/\.stx-memory-maintenance-icon\s*\{[^}]*width:\s*34px[^}]*height:\s*34px[^}]*place-items:\s*center/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-danger-actions\s+\.stx-memory-danger-action\[data-ss-helper-control="button"\][^}]*grid-template-columns:\s*30px\s+minmax\(0,\s*1fr\)[^}]*text-align:\s*left/u);
    expect(source).toContain('<ss-helper-icon name="file-export" decorative>');
    expect(source).not.toContain('<ss-helper-icon name="file-import" decorative>');
    expect(source).not.toContain('import-file');
    expect(source).toContain('<ss-helper-icon name="eraser" decorative>');
    expect(source).not.toContain('fa-solid');
    expect(source).toContain('本聊天记忆占用');
    expect(source).toContain('数据库 / WAL 占用');
    expect(styles).not.toMatch(/\.stx-memory-search-wrap\s+\[data-ss-helper-control="input"\]\s*\{[^}]*padding/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-page-heading\s*\{[^}]*min-height:\s*42px/u);
    expect(styles).toMatch(/\.stx-memory-page-heading\s*>\s*div\s*\{[^}]*display:\s*grid/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-page-heading\s+h2,[^}]*\.stx-memory-page-heading\s+p\s*\{[^}]*margin:\s*0/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-detail-head\s*>\s*div\s*\{[^}]*display:\s*flex[^}]*align-items:\s*center/u);
    expect(source).toContain("class='stx-memory-page-refresh'");
    expect(source).toContain("data-action='refresh'");
    expect(source).toContain('memoryPluginConfig.manifest.version');
    expect(styles).toMatch(/\.stx-memory-error-guidance\s*\{[^}]*display:\s*grid[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto/u);
    expect(styles).toMatch(/\.stx-memory-error-request\s*\{[^}]*justify-self:\s*end[^}]*font-size:\s*\.52rem/u);
    expect(styles).toMatch(/\.stx-memory-page-content:has\(> section\.stx-memory-panel\)[^}]*grid-template-columns/u);
    expect(styles).toMatch(/\.stx-memory-audit-split\s*\{[^}]*grid-template-columns:\s*minmax\(18rem,\s*\.78fr\)\s+minmax\(28rem,\s*1\.22fr\)/u);
    expect(styles).toMatch(/\.stx-memory-audit-shell\[data-audit-mobile-view="list"\]\s+\.stx-memory-audit-detail\s*\{[^}]*display:\s*none/u);
    expect(styles).toMatch(/\.stx-memory-usage-chart-stage\s*\{[^}]*position:\s*relative[^}]*height:\s*220px/u);
    expect(styles).toMatch(/\.stx-memory-page-content:has\(> \.stx-memory-card-grid\)[^}]*grid-template-rows/u);
    expect(styles).toMatch(/\.stx-memory-multi-filter-menu\s*\{[^}]*position:\s*absolute[^}]*max-height:/u);
    expect(styles).toMatch(/\.stx-memory-multi-filter-option\s*\{[^}]*display:\s*flex/u);
    expect(styles).toMatch(/\.stx-memory-multi-filter-menu\s*\{[^}]*display:\s*grid[^}]*gap:\s*4px/u);
    expect(styles).toMatch(/\.stx-memory-multi-filter-option\.is-selected,\s*\.stx-memory-multi-filter-option\.is-partial\s*\{[^}]*border-color:\s*transparent[^}]*background:\s*transparent/u);
    expect(styles).not.toMatch(/\.stx-memory-multi-filter-option\.is-selected[^,{]*\{[^}]*border-left-color:/u);
    expect(styles).toMatch(/input\.stx-memory-multi-filter-native\[data-ss-helper-control="checkbox"\]\s*\{[^}]*clip-path:\s*inset\(50%\)[^}]*opacity:\s*0/u);
    expect(source).toContain('<ss-helper-icon name="check" decorative>');
    expect(source).not.toContain('fa-square-check');
    expect(source).not.toContain('fa-regular');
    expect(styles).toMatch(/\.stx-memory-card-grid\s*\{[^}]*min-height:\s*100%/u);
    expect(styles).toMatch(/\.stx-memory-reinitialize-drawer\s*\{[^}]*background-color:\s*var\(--ss-theme-surface,\s*#1b1b1a\)[^}]*animation:\s*stx-memory-reinitialize-drawer-in/u);
    expect(styles).toMatch(/\.stx-memory-drawer-backdrop\s*\{[^}]*background:\s*rgba\(0,\s*0,\s*0,\s*\.62\)[^}]*animation:\s*stx-memory-reinitialize-backdrop-in/u);
    expect(styles).toContain('@keyframes stx-memory-reinitialize-drawer-in');
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-multi-filter-trigger\[data-ss-helper-control="button"\]\s*\{[^}]*display:\s*grid[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+24px[^}]*justify-content:\s*stretch/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-fact-row\[data-ss-helper-control="button"\]\s*\{[^}]*min-height:\s*116px[^}]*display:\s*grid[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)[^}]*align-items:\s*stretch[^}]*border-color:\s*transparent/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-library-fact-list\s*\{[^}]*grid-auto-rows:\s*max-content/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-library-fact-row\[data-ss-helper-control="button"\]\s*\{[^}]*min-height:\s*116px/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-scenes-shell\s*\{[^}]*height:\s*100%[^}]*grid-template-rows:\s*auto\s+minmax\(0,\s*1fr\)[^}]*overflow:\s*hidden/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-scene-record-grid\s*\{[^}]*height:\s*100%[^}]*overflow:\s*hidden/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-scene-record-list\s*\{[^}]*grid-auto-rows:\s*116px[^}]*overflow:\s*auto/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-scene-record-row\s*\{[^}]*height:\s*116px[^}]*overflow:\s*hidden/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-scene-aside\s*\{[^}]*padding:\s*0[^}]*border:\s*0[^}]*background:\s*transparent[^}]*box-shadow:\s*none/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-fact-row\[data-ss-helper-control="button"\]\[aria-selected="true"\]\s*\{[^}]*border-color:\s*color-mix/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-graph-edge-top\s*\{[^}]*display:\s*grid[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+auto[^}]*overflow:\s*visible/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-graph-edge-row\[data-ss-helper-control="button"\]\s*\{[^}]*min-height:\s*54px[^}]*overflow:\s*visible/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-graph-edge-top\s*>\s*span\s*\{[^}]*flex-wrap:\s*nowrap[^}]*white-space:\s*nowrap/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-graph-edge-list::-webkit-scrollbar-button\s*\{[^}]*display:\s*none/u);
    expect(styles).toMatch(/\.stx-memory-workbench\s+\.stx-memory-graph-list-switch\s+\[role="tab"\]\[aria-selected="false"\]\s*\{[^}]*border-color:\s*transparent[^}]*box-shadow:\s*none/u);
    const graphListModeSync = source.slice(source.indexOf('const syncGraphListMode'), source.indexOf('const renderAudit'));
    expect(graphListModeSync).not.toContain('syncGraphUi(');
    expect(graphListModeSync).not.toContain('graphView(');
    expect(graphListModeSync).toContain('window.requestAnimationFrame');
    expect(styles).not.toContain('backdrop-filter: blur(14px)');
    expect(memoryUiSource).toContain("uiControl('segmented')");
    expect(memoryUiSource).toContain('data-memory-usage-chart');
    expect(memoryUiSource).toContain('class="stx-memory-usage-table" role="region"');
    expect(memoryUiSource).not.toContain('class="stx-memory-usage-table" role="table"');
    expect(memoryUiSource).toContain('/^[=+\\-@]/u');
    expect(memoryUiSource).toContain('popupUi.confirm({');
    expect(memoryUiSource).toContain("{ id: 'data', label: '数据维护'");
    expect(memoryUiSource).not.toMatch(/window\.toastr|\btoastr\./u);
    expect(memoryUiSource).not.toContain('<svg');
    expect(memoryUiSource).not.toMatch(/<button[^>]*>\s*(?:←|→|✓|✕|×|⋮)/u);
    expect(memoryUiSource).not.toContain('error.message');
    expect(memoryUiSource).not.toContain('candidateSnapshot');
    expect(memoryUiSource).toContain('mountInventoryCardThree');
    expect(memoryUiSource).toContain('selectInventoryWorkbenchModel');
    expect(memoryUiSource).toContain("data-action=\"inventory-create-open\"");
    expect(memoryUiSource).toContain('data-inventory-select="precision"');
    expect(memoryUiSource).toContain('data-inventory-split="detail"');
    expect(memoryUiSource).toContain('data-inventory-split="preview"');
    expect(memoryUiSource).toContain('requestInventorySelection(itemId)');
    expect(memoryUiSource).toContain('INVENTORY_CARD_TRANSITION_MS');
    expect(memoryUiSource).toContain('popupUi.confirm({');
    expect(inventoryModelSource).toContain("quantity.availability === 'absent'");
    expect(inventoryThreeSource).toContain("new URL('./assets/inventory-card-front.webp', import.meta.url)");
    expect(inventoryThreeSource).toContain("new URL('./assets/inventory-card-back.webp', import.meta.url)");
    expect(inventoryThreeSource).toContain('new THREE.ExtrudeGeometry');
    expect(inventoryThreeSource).not.toContain('new THREE.TorusGeometry');
    expect(inventoryThreeSource).toContain('float cellular(vec2 point)');
    expect(inventoryThreeSource).toContain("particleGeometry.setAttribute('aBlink'");
    expect(inventoryThreeSource).toContain('MAX_INVENTORY_CARD_PIXEL_RATIO = 1.5');
    expect(inventoryThreeSource).toContain('new ResizeObserver(resize)');
    expect(inventoryThreeSource).toContain('new IntersectionObserver');
    expect(inventoryThreeSource).toContain('teardown(false)');
    expect(inventoryThreeSource).toContain('teardown(true)');
    expect(inventoryThreeSource).not.toMatch(/https?:\/\/(?:cdn|unpkg|jsdelivr)/u);
    expect(inventoryThreeSource).not.toContain('data:image');
    expect(`${memoryUiSource}\n${inventoryThreeSource}`).not.toContain('<svg');
    expect(styles).toMatch(/\.stx-memory-inventory-console\s*\{[^}]*grid-template-columns:\s*166px\s+minmax\(360px,\s*1fr\)\s+12px\s+minmax\(300px,\s*var\(--stx-inventory-detail-width\)\)/u);
    expect(styles).toMatch(/@media \(max-width:\s*900px\)[\s\S]*?\.stx-memory-inventory-console\s*\{[^}]*grid-template-columns:\s*1fr/u);
    expect(styles).toMatch(/@media \(max-width:\s*900px\)[\s\S]*?\.stx-memory-inventory-splitter\s*\{[^}]*display:\s*none/u);
    expect(styles).toContain('@keyframes stx-memory-inventory-card-leave');
    expect(styles).toContain('@keyframes stx-memory-inventory-card-enter');
    expect(styles).toMatch(/animation:\s*stx-memory-inventory-card-leave\s+300ms/u);
    expect(styles).toMatch(/animation:\s*stx-memory-inventory-card-enter\s+380ms/u);
    const inventoryTransitions = styles.slice(styles.indexOf('[data-inventory-transition="leaving"]'), styles.indexOf('.stx-memory-workbench .stx-memory-inventory-hero'));
    expect(inventoryTransitions).not.toMatch(/filter:|brightness\(|background:/u);
    expect(inventoryTransitions).not.toContain('stx-memory-inventory-card-canvas');
    expect(inventoryThreeSource).toContain("Object.assign(flightTarget, { x: -2.7");
    expect(styles).toMatch(/@media \(max-width:\s*540px\)[\s\S]*?\.stx-memory-inventory-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(116px,\s*1fr\)\)/u);
    expect(styles).toMatch(/@media \(max-width:\s*540px\)[\s\S]*?\.stx-memory-inventory-create-fields\s*\{[^}]*grid-template-columns:\s*1fr/u);
    const nativeSelects = memoryUiSource.match(/<select\b[^>]*>/gu) ?? [];
    expect(nativeSelects.length).toBeGreaterThan(0);
    expect(nativeSelects.every(tag => tag.includes("${uiControl('select')}"))).toBe(true);
    const exportSource = memoryUiSource.slice(memoryUiSource.indexOf("if (action === 'export-audit')"), memoryUiSource.indexOf("if (action === 'rollback-audit')"));
    expect(exportSource).not.toMatch(/candidateSnapshot|promptSnapshot|injectedPrompt|providerError(?:Code|Type|Param)/u);
    expect(source).not.toMatch(/\bstx-ui-/u);
    expect(styles).not.toMatch(/\bstx-ui-/u);
    expect(styles).not.toMatch(/--memory-/u);
    expect(`${source}\n${styles}`).not.toMatch(/\bstx-memory-(?:button|input|chip|select-wrap)\b/u);
  });
});
